# Generated by Django 4.0.5 on 2022-07-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitores',
            name='avatars',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
