# Generated by Django 4.0.5 on 2022-07-28 15:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_monitores_avatars'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitores',
            name='descripcion',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='monitores',
            name='avatars',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
    ]
